export const ArticleData = [
  {
    id: 1,
    title: "নারীবাদ প্রসঙ্গ : শিক্ষিত নারীদের করার কিছুই নেই?",
    image: "./images/Feminism.webp",
    description: "কুরআনের মাধ্যমে জীবনের সত্যিকার অর্থ খুঁজে নেওয়ার একটি গল্প।",
    link: "/articles/quran-alo",
  },
  {
    id: 2,
    title: "শাইখ আসিম আল-বারকাওয়ি : তাওহিদের জীবন্ত চিহ্ন",
    image: "./images/Sheikh Asim.jpg",
    description: "প্রিয় নবী (সা.)-এর জীবনধারা থেকে অনুপ্রেরণা নিন প্রতিদিন।",
    link: "/articles/quran-alo",
  },
  {
    id: 3,
    title: "সালাফদের আকিদাহ : সিফাতের প্রকাশ্য অর্থগ্রহণ",
    image: "./images/TheCreed.webp",
    description: "দু’আ কেন কবুল হয় না? এবং কিভাবে হৃদয় থেকে দু’আ করা যায়।",
    link: "/articles/quran-alo",
  },
  {
    id: 4,
    title: "তাফসির শেখার প্রথম ধাপ",
    image: "./images/Feminism.webp",
    description:
      "তাফসির শেখার জন্য প্রয়োজনীয় ভিত্তি ও উপযুক্ত উৎস নিয়ে আলোচনা।",
    link: "/articles/quran-alo",
  },
  {
    id: 5,
    title: "আখলাক ও চরিত্র",
    image: "./images/Feminism.webp",
    description: "একজন মুসলিমের জীবনে উত্তম চরিত্রের ভূমিকা ও গুরুত্ব।",
    link: "/articles/quran-alo",
  },
  {
    id: 6,
    title: "ইলম অর্জনের আদব",
    image: "./images/Feminism.webp",
    description:
      "শিক্ষা অর্জনের ইসলামি আদবগুলো জানা একজন ছাত্রের জন্য অপরিহার্য।",
    link: "/articles/quran-alo",
  },
  {
    id: 7,
    title: "দুনিয়া ও আখিরাতের ভারসাম্য",
    image: "./images/Feminism.webp",
    description: "কীভাবে দুনিয়ার কাজ ও আখিরাতের চিন্তাকে একসাথে রাখা যায়।",
    link: "/articles/quran-alo",
  },
  {
    id: 8,
    title: "রিয়াজ ও নিয়তের পার্থক্য",
    image: "./images/Feminism.webp",
    description: "আমাদের আমলের মূল হচ্ছে নিয়ত, বাহ্যিক রিয়াজ নয়।",
    link: "/articles/quran-alo",
  },
  {
    id: 9,
    title: "নবীজির দোয়া",
    image: "./images/Feminism.webp",
    description: "রাসূলুল্লাহ (সা.)-এর দোয়া থেকে আমাদের জীবনের দিকনির্দেশনা।",
    link: "/articles/quran-alo",
  },
  {
    id: 10,
    title: "নামাজে খুশু",
    image: "./images/Feminism.webp",
    description: "কীভাবে নামাজে মনোযোগ এবং খুশু বৃদ্ধি করা যায়।",
    link: "/articles/quran-alo",
  },
  {
    id: 11,
    title: "রামাদানের শিক্ষা",
    image: "./images/Feminism.webp",
    description: "রামাদান শুধু রোজা নয়, আত্মশুদ্ধির এক অনন্য সময়।",
    link: "/articles/quran-alo",
  },
  {
    id: 12,
    title: "আল্লাহর স্মরণ",
    image: "https://images.unsplash.com/photo-1508154048109-de555266b70a",
    description: "জিকিরের মাধ্যমে অন্তরে প্রশান্তি আসে।",
    link: "/articles/quran-alo",
  },
  {
    id: 13,
    title: "দান ও সাদাকা",
    image: "https://images.unsplash.com/photo-1522202195465-dc1c1d5e3a4e",
    description: "দান হলো আত্মার পরিশুদ্ধির একটি মহৎ উপায়।",
    link: "/articles/quran-alo",
  },
  {
    id: 14,
    title: "কোরআন তিলাওয়াতের ফজিলত",
    image: "https://images.unsplash.com/photo-1568043210943-0e56c0f1a26e",
    description: "কুরআন তিলাওয়াতকারীর জন্য রয়েছে অসংখ্য সওয়াব ও বরকত।",
    link: "/articles/quran-alo",
  },
  {
    id: 15,
    title: "ইমানের শক্তি",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    description: "ইমানই হলো একজন মুসলিমের জীবনের সর্বশ্রেষ্ঠ সম্পদ।",
    link: "/articles/quran-alo",
  },
  {
    id: 16,
    title: "হালাল রিজিক",
    image: "https://images.unsplash.com/photo-1590080875831-f9a18d94dcf0",
    description: "হালাল রিজিকের গুরুত্ব এবং বরকতপূর্ণ জীবনের রহস্য।",
    link: "/articles/quran-alo",
  },
  {
    id: 17,
    title: "অহংকারের পরিণতি",
    image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    description: "অহংকার মানুষকে আল্লাহর রহমত থেকে বঞ্চিত করে।",
    link: "/articles/quran-alo",
  },
  {
    id: 18,
    title: "সদাচরণে সফলতা",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b",
    description: "মানুষের সাথে সুন্দর আচরণ সফল জীবনের চাবিকাঠি।",
    link: "/articles/quran-alo",
  },
  {
    id: 19,
    title: "আল্লাহর প্রতি তাওয়াক্কুল",
    image: "https://images.unsplash.com/photo-1519074002996-a69e7ac46a42",
    description: "বিশ্বাস রাখুন, আল্লাহ আপনার জন্য উত্তম পরিকল্পনাই রেখেছেন।",
    link: "/articles/quran-alo",
  },
  {
    id: 20,
    title: "শেষ বিচারের দিন",
    image: "https://images.unsplash.com/photo-1549880338-65ddcdfd017b",
    description: "কিয়ামতের দিনের স্মরণ মানুষকে আল্লাহভীতির দিকে নিয়ে যায়।",
    link: "/articles/quran-alo",
  },
];
